server:
  port: 0
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: chat-service
  cloud:
    config:
      name: trend-chat-dev, chat-service-dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI}